### ISSUE TITLE
package.json incorrecto

### ISSUE THREAD

**Issue by damianwajser** [Nof84/node-app-example#2]
{
  "name": "node-api-rest",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "body-parser": "~1.15.1",
    "cookie-parser": "~1.4.3",
    "debug": "~2.2.0",
    "express": "~4.13.4",
    "jade": "~1.11.0",
    "morgan": "~1.7.0",
    "serve-favicon": "~2.3.0",
    "mongoose": "~4.6.1"
  }
}

tenes dependencias de mas...

{
  "name": "node-api-rest",
  "version": "0.0.0",
  "dependencies": {
    "body-parser": "~1.15.1",
    "express": "~4.13.4",
    "morgan": "~1.7.0",
    "mongoose": "~4.6.1"
  }
}

**Comment by Nof84** [comment]
Correcto, el package.json lo había armado originalmente con Express. Ahi los elimino.

Gracias

Nof
